project_name: hystrix_exporter
release:
  github:
    owner: ContaAzul
    name: hystrix_exporter
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
archive:
  files:
  - config.yml
dockers:
- image: caninjas/hystrix_exporter
  latest: true
