dist: trusty
sudo: required
language: go
go: 1.9
services:
  - docker
install:
  - make setup
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - make ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email: false
